from enum import Enum


class MethodName(Enum):
    GetHotelList = "getHotelList"
    GetHotelListByFilter = "getHotelListByFilter"
    GetSpecialList = "getSpecialList"
    GetRoomList = "getRoomList"
    GetWidgetConfig = "getWidgetConfig"
    GetPriceList = "getPriceList"
    GetAvailability = "getAvailability"
    GetRoomAvailability = "getRoomAvailability"
    GetDayAvailability = "getDayAvailability"
    PrepareBooking = "prepareBooking"
    GetBooking = "getBooking"
    CancelBooking = "cancelBooking"
    CreateInquiry = "createInquiry"
    GetInquiry = "getInquiry"
    GetUserSources = "getUserSources"
    GetLocationList = "getLocationList"
    GetMasterpackagesList = "getMasterpackagesList"
    NotifyMasterpackages = "notifyMasterpackages"
    GetThemeList = "getThemeList"
    GetLastminuteQuotations = "getLastminuteQuotations"
    GetHotelPictures = "getHotelPictures"
    GetHotelPictureGroups = "getHotelPictureGroups"
    GetOptionalServices = "getOptionalServices"
    ValidateCoupon = "validateCoupon"
